name: Cypress tests
 
on: [push]
 
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
    - uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        browser: ${{ matrix.browser }}
    - name: Upload screenshots and videos on error 📦
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Cypress screenshots and videos
        path: |
          cypress/screenshots
          cypress/videos